# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20171128_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
