# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_remove_like_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
