# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u0437\u0430\u0433\u0430\u043b\u043e\u0432\u043e\u043a')),
                ('company', models.CharField(max_length=100, verbose_name='\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f')),
                ('description', models.TextField(default='', verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.IntegerField(verbose_name='\u0446\u0435\u043d\u0430')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_edit', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d',
                'verbose_name_plural': '\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d\u044b',
            },
        ),
    ]
